### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xcypher78** [0x1x02/GLiNet-Router-Auth-Bypass#1]
File "/GLiNet-Router-Auth-Bypass-main/exploit.py", line 28
    f"roo[^'union selecT
    ^
SyntaxError: unterminated string literal (detected at line 28)

**Comment by 0x1x02** [comment]
Hi @xcypher78 ,

Thank you for bringing this to our attention. It appears there's a syntax error due to an unterminated string literal in the exploit.py file. We've addressed the issue and pushed a fix to the repository.

Please pull the latest changes and try running the script again. If you encounter any further issues, do not hesitate to report them.

Best regards,

0x1x02
